apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app-of-apps
  namespace: argocd
spec:
  project: hello-world-project
  source:
    repoURL: 'https://github.com/elgazali/test'
    targetRevision: HEAD
    path: argo-apps/hello-world-apps
  destination:
    server: https://kubernetes.default.svc
